apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vr1l
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xsbx-tenant/rhtap-demo-app/hacbs-test-project-vr1l@sha256:f4da1c8b197250d01a71a3602fe41648d2447384c05e975ee176cd180c76d5b3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
