apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vr1l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vr1l
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vr1l
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vr1l
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vr1l
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xsbx-tenant/rhtap-demo-app/hacbs-test-project-vr1l@sha256:cb012df59281ffefec681aa8a808176e5fccbc70545dcd2e72ac43f88c8408c7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
